"""pakeiciau login_security

Revision ID: 2549abbdb0b7
Revises: 9beb88966cba
Create Date: 2025-07-28 20:42:40.994526

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2549abbdb0b7'
down_revision = '9beb88966cba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_security', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('login_security_ibfk_2'), type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('login_security', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key(batch_op.f('login_security_ibfk_2'), 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###
