"""updeitinau review lentele dadejau timestampa

Revision ID: 9091ed7d3b8e
Revises: 32448b76cbec
Create Date: 2025-07-31 13:07:30.971599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9091ed7d3b8e'
down_revision = '32448b76cbec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_review_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_timestamp'))
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
