"""Pridėtas image_filename prie Product

Revision ID: 984755a664d6
Revises: 9091ed7d3b8e
Create Date: 2025-07-31 22:29:55.214960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '984755a664d6'
down_revision = '9091ed7d3b8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
