"""pridedu car klase su rysiais

Revision ID: a0d96b06a1dc
Revises: 6ad0cfceda4f
Create Date: 2025-07-30 19:04:02.780272

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a0d96b06a1dc'
down_revision = '6ad0cfceda4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cart',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('modifiedBy', sa.String(length=50), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('modifiedDate', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'product_id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.TEXT(collation='utf8mb4_lithuanian_ci'), nullable=True),
    sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('product_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('createdBy', mysql.VARCHAR(collation='utf8mb4_lithuanian_ci', length=50), nullable=False),
    sa.Column('modifiedBy', mysql.VARCHAR(collation='utf8mb4_lithuanian_ci', length=50), nullable=False),
    sa.Column('createdDate', mysql.DATETIME(), nullable=True),
    sa.Column('modifiedDate', mysql.DATETIME(), nullable=True),
    sa.Column('deleted', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('review_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('review_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_lithuanian_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )

    # ### end Alembic commands ###
