"""Pridedu user_role lauką User lentelėje

Revision ID: d6ddce8f6935
Revises: 
Create Date: 2025-07-24 21:58:32.612941

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6ddce8f6935'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_name', sa.String(length=50), nullable=False),
    sa.Column('user_lastname', sa.String(length=50), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=False),
    sa.Column('user_password', sa.String(length=100), nullable=False),
    sa.Column('user_role', sa.Integer(), nullable=False),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('modifiedBy', sa.String(length=50), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('modifiedDate', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
