"""pridėtas prisijungimų tikrinimas

Revision ID: eca12b35d8d0
Revises: d6ddce8f6935
Create Date: 2025-07-25 13:38:05.346077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eca12b35d8d0'
down_revision = 'd6ddce8f6935'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('blocked_until', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('blocked_until')
        batch_op.drop_column('login_attempts')

    # ### end Alembic commands ###
