"""Pridėti product

Revision ID: f707048f99d3
Revises: 2549abbdb0b7
Create Date: 2025-07-29 19:47:20.345349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f707048f99d3'
down_revision = '2549abbdb0b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('createdBy', sa.String(length=50), nullable=False),
    sa.Column('modifiedBy', sa.String(length=50), nullable=False),
    sa.Column('createdDate', sa.DateTime(), nullable=True),
    sa.Column('modifiedDate', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('products')
    # ### end Alembic commands ###
